def get_odd_collatz(n):
    """
    GIVEN A POSITIVE INTEGER N, RETURN A SORTED LIST THAT HAS THE ODD NUMBERS IN COLLATZ SEQUENCE.

    THE COLLATZ CONJECTURE IS A CONJECTURE IN MATHEMATICS THAT CONCERNS A SEQUENCE DEFINED
    AS FOLLOWS: START WITH ANY POSITIVE INTEGER N. THEN EACH TERM IS OBTAINED FROM THE 
    PREVIOUS TERM AS FOLLOWS: IF THE PREVIOUS TERM IS EVEN, THE NEXT TERM IS ONE HALF OF 
    THE PREVIOUS TERM. IF THE PREVIOUS TERM IS ODD, THE NEXT TERM IS 3 TIMES THE PREVIOUS
    TERM PLUS 1. THE CONJECTURE IS THAT NO MATTER WHAT VALUE OF N, THE SEQUENCE WILL ALWAYS REACH 1.

    NOTE: 
        1. COLLATZ(1) IS [1].
        2. RETURNED LIST SORTED IN INCREASING ORDER.

    FOR EXAMPLE:
    GET_ODD_COLLATZ(5) RETURNS [1, 5] # THE COLLATZ SEQUENCE FOR 5 IS [5, 16, 8, 4, 2, 1], SO THE ODD NUMBERS ARE ONLY 1, AND 5.
    """
    if n <= 0:
        return []
    
    odd_numbers = set()
    while n != 1:
        if n % 2 != 0:
            odd_numbers.add(n)
            n = 3 * n + 1
        else:
            n = n // 2
    odd_numbers.add(1)
    return sorted(list(odd_numbers))