def fruit_distribution(s,n):
    """
    IN THIS TASK, YOU WILL BE GIVEN A STRING THAT REPRESENTS A NUMBER OF APPLES AND ORANGES 
    THAT ARE DISTRIBUTED IN A BASKET OF FRUIT THIS BASKET CONTAINS 
    APPLES, ORANGES, AND MANGO FRUITS. GIVEN THE STRING THAT REPRESENTS THE TOTAL NUMBER OF 
    THE ORANGES AND APPLES AND AN INTEGER THAT REPRESENT THE TOTAL NUMBER OF THE FRUITS 
    IN THE BASKET RETURN THE NUMBER OF THE MANGO FRUITS IN THE BASKET.
    FOR EXAMDLE:
    FRUIT_DISTRIBUTION("5 APPLES AND 6 ORANGES", 19) ->19 - 5 - 6 = 8
    FRUIT_DISTRIBUTION("0 APPLES AND 1 ORANGES",3) -> 3 - 0 - 1 = 2
    FRUIT_DISTRIBUTION("2 APPLES AND 3 ORANGES", 100) -> 100 - 2 - 3 = 95
    FRUIT_DISTRIBUTION("100 APPLES AND 1 ORANGES",120) -> 120 - 100 - 1 = 19
    """
    parts = s.split(" ")
    apples = int(parts[0])
    oranges = int(parts[3])
    mangoes = n - apples - oranges
    return mangoes