def hex_key(num):
    """YOU HAVE BEEN TASKED TO WRITE A FUNCTION THAT RECEIVES 
    A HEXADECIMAL NUMBER AS A STRING AND COUNTS THE NUMBER OF HEXADECIMAL 
    DIGITS THAT ARE PRIMES (PRIME NUMBER, OR A PRIME, IS A NATURAL NUMBER 
    GREATER THAN 1 THAT IS NOT A PRODUCT OF TWO SMALLER NATURAL NUMBERS).
    HEXADECIMAL DIGITS ARE 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F.
    PRIME NUMBERS ARE 2, 3, 5, 7, 11, 13, 17,...
    SO YOU HAVE TO DETERMINE A NUMBER OF THE FOLLOWING DIGITS: 2, 3, 5, 7, 
    B (=DECIMAL 11), D (=DECIMAL 13).
    NOTE: YOU MAY ASSUME THE INPUT IS ALWAYS CORRECT OR EMPTY STRING, 
    AND SYMBOLS A,B,C,D,E,F ARE ALWAYS UPPERCASE.
    EXAMPLES:
    FOR NUM = "AB" THE OUTPUT SHOULD BE 1.
    FOR NUM = "1077E" THE OUTPUT SHOULD BE 2.
    FOR NUM = "ABED1A33" THE OUTPUT SHOULD BE 4.
    FOR NUM = "123456789ABCDEF0" THE OUTPUT SHOULD BE 6.
    FOR NUM = "2020" THE OUTPUT SHOULD BE 2.
    """
    count = 0
    for digit in num:
        if digit == '2' or digit == '3' or digit == '5' or digit == '7':
            count += 1
        elif digit == 'B' or digit == 'D':
            count += 1
    return count